#! /bin/sh
# /etc/init.d/noip 

### BEGIN INIT INFO
# Provides:          iqaudioamp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Unmute / mute amp at boot / shutdown
# Description:       
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Unmuting iqaudio amp"
    # run application you want to start
    gpio -g mode 22 out
    gpio -g write 22 1
    ;;
  stop)
    echo "Muting iqaudio amp"
    gpio -g mode 22 out
    gpio -g write 22 0
    ;;
  *)
    echo "Usage: /etc/init.d/iqaudioamp {start|stop}"
    exit 1
    ;;
esac

exit 0
